In [2]:
# Installing A Python API for accessing music charts from Billboard.com.

!pip install billboard.py

Requirement already satisfied: billboard.py in c:\users\bivan\appdata\local\programs\python\python39\lib\site-packages (7.0.0)

WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the 'c:\users\bivan\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: beautifulsoup4>=4.4.1 in c:\users\bivan\appdata\local\programs\python\python39\lib\site-packages (from billboard.py) (4.11.1)
Requirement already satisfied: requests>=2.2.1 in c:\users\bivan\appdata\local\programs\python\python39\lib\site-packages (from billboard.py) (2.25.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\bivan\appdata\local\programs\python\python39\lib\site-packages (from beautifulsoup4>=4.4.1->billboard.py) (2.3.2.post1)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\bivan\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.2.1->billboard.py) (2020.12.5)
Requirement already satisfied: idna<3,>=2.5 in c:\users\bivan\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.2.1->billboard.py) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\bivan\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.2.1->billboard.py) (1.26.4)
Requirement already satisfied: chardet<5,>=3.0.2 in c:\users\bivan\appdata\local\programs\python\python39\lib\site-packages (from requests>=2.2.1->billboard.py) (4.0.0)

In [3]:
# Importing billboard to load data from Billboard.com
import billboard
# Importing pandas to convert data into DataFrame
import pandas as pd

In [7]:
#artists: top 10 artists in all years.
artists = [] 
#year: year wise loading songs.
year = 2021 
for y in range(2022-2006):
    #chart: It contains data from Billboard which include artists names and title of songs
    chart = billboard.ChartData('Top-Artists', year=year)
    cnt = 0
    for chr in chart:
        cnt += 1
        if chr.artist not in artists:
                artists.append(chr.artist)
        #cnt: Stop itration when we get top 10 artists every year.        
        if cnt == 10:
            break
    
    year -= 1
#Collected Top 80 artists from 2006 - 2021
print(artists)
len(artists)

['Drake', 'Olivia Rodrigo', 'The Weeknd', 'Taylor Swift', 'Morgan Wallen', 'Ariana Grande', 'Doja Cat', 'Justin Bieber', 'Luke Combs', 'Pop Smoke', 'Post Malone', 'Roddy Ricch', 'DaBaby', 'Juice WRLD', 'Lil Baby', 'Harry Styles', 'Billie Eilish', 'Khalid', 'Travis Scott', 'Ed Sheeran', 'Lil Nas X', 'Halsey', 'Cardi B', 'XXXTENTACION', 'Imagine Dragons', 'BTS', 'Bruno Mars', 'Camila Cabello', 'Kendrick Lamar', 'The Chainsmokers', 'Future', 'Shawn Mendes', 'Adele', 'Beyonce', 'twenty one pilots', 'Rihanna', 'Coldplay', 'One Direction', 'Maroon 5', 'Meghan Trainor', 'Fetty Wap', 'Sam Smith', 'Nicki Minaj', 'Katy Perry', 'Justin Timberlake', 'Iggy Azalea', 'Miley Cyrus', 'Pharrell Williams', 'Eminem', 'Macklemore & Ryan Lewis', 'P!nk', 'LMFAO', 'Lady Gaga', 'Lil Wayne', 'Chris Brown', 'Lady A', 'Ke$ha', 'Usher', 'The Black Eyed Peas', 'Kanye West', 'Britney Spears', 'T.I.', 'Nickelback', 'Alicia Keys', 'Leona Lewis', 'Jordin Sparks', 'Jonas Brothers', 'Akon', 'Fergie', 'Daughtry', 'Carrie Underwood', 'Avril Lavigne', 'T-Pain', 'Gwen Stefani', 'Rascal Flatts', 'Sean Paul', 'Ne-Yo', 'The Pussycat Dolls', 'Mary J. Blige', 'The Fray']

80

In [5]:
def getData(type, data, artists, titles, year=None, date=None, label=None): #type means type of chart we get from Billboard.
    if date==None: #data is a list of dictionary we collocet data into.
        HotChart = billboard.ChartData(type, year=year) #year to use it when collect popular data.
    else:
        HotChart = billboard.ChartData(type, date=date) #date to use it when collect unpopular data.
    for hot in HotChart:
        # To collect the name of artists that exists in the artist's list and choose another song for the same artist.
        # This is to avoid repeat songs and enter artist doesn't exist in artists list.
        if hot.title not in titles and hot.artist in artists: #titles is a list of songs name use it to avoid repeat songs.
                titles.append(hot.title)
                data.append({'Artist': hot.artist, 'Title': hot.title, 'Label': label}) #label is 1 if popular and 0 if unpopular.
    
    return data, titles

In [8]:
data = []
titles = []
year = 2021
for i in range(2022-2006):
    data, titles = getData('Hot-100-Songs', data, artists, titles, year, label=1) # popular songs
    year -= 1

In [9]:
#We collect popular data from 2006 to 2021
print(len(data))
print(len(artists))
print(len(titles))

403
80
403

In [10]:
# Splited the year into 4 splits to get a lot of songs with the same artists which I choose and used the same techniques for every year.
dates = ['2021-12-01','2021-08-01','2021-04-01','2021-01-01',
        '2020-12-01','2020-08-01','2020-04-01','2020-01-01',
        '2019-12-01','2019-08-01','2019-04-01','2019-01-01',
        '2018-12-01','2018-08-01','2018-04-01','2018-01-01',
        '2017-12-01','2017-08-01','2017-04-01','2017-01-01',
        '2016-12-01','2016-08-01','2016-04-01','2016-01-01',
        '2015-12-01','2015-08-01','2015-04-01','2015-01-01',
        '2014-12-01','2014-08-01','2014-04-01','2014-01-01',
        '2013-12-01','2013-08-01','2013-04-01','2013-01-01',
        '2012-12-01','2012-08-01','2012-04-01','2012-01-01',
        '2011-12-01','2011-08-01','2011-04-01','2011-01-01',
        '2010-12-01','2010-08-01','2010-04-01','2010-01-01',
        '2009-12-01','2009-08-01','2009-04-01','2009-01-01',
        '2008-12-01','2008-08-01','2008-04-01','2008-01-01',
        '2007-12-01','2007-08-01','2007-04-01','2007-01-01',
        '2006-12-01','2006-08-01','2006-04-01','2006-01-01']
for date in dates:
    data, titles = getData('hot-100', data, artists, titles, date=date, label=0) # To get unpopular songs

In [11]:
#Printed unpopular data from 2006 to 2021
print(len(data))
print(len(artists))
print(len(titles))

809
80
809

In [12]:
# Converted data to dataframe by using pandas
df = pd.DataFrame(data)
df

             Artist                           Title  Label
0        The Weeknd                 Blinding Lights      1
1    Olivia Rodrigo                        Good 4 U      1
2    Olivia Rodrigo                 Drivers License      1
3         Lil Nas X  Montero (Call Me By Your Name)      1
4               BTS                          Butter      1
..              ...                             ...    ...
804    Gwen Stefani                       Luxurious      0
805         Rihanna    If It's Lovin' That You Want      0
806       Lil Wayne                         Fireman      0
807     Alicia Keys                     Unbreakable      0
808   Rascal Flatts                 Skin (Sarabeth)      0

[809 rows x 3 columns]

In [13]:
# It shows all songs by Drake
df[df['Artist']=='Drake']

    Artist                    Title  Label
19   Drake              What's Next      1
34   Drake             Toosie Slide      1
76   Drake               God's Plan      1
78   Drake           In My Feelings      1
79   Drake            Nice For What      1
90   Drake                  Nonstop      1
99   Drake                I'm Upset      1
111  Drake                Fake Love      1
120  Drake             Passionfruit      1
136  Drake            Hotline Bling      1
142  Drake                Controlla      1
177  Drake             Back To Back      1
191  Drake  0 To 100 / The Catch Up      1
199  Drake  Started From The Bottom      1
266  Drake                Headlines      1
276  Drake           Find Your Love      1
282  Drake                     Over      1
302  Drake          Best I Ever Had      1
526  Drake                 Mob Ties      0
532  Drake              Emotionless      0
533  Drake        Can't Take A Joke      0
554  Drake                    Signs      0
572  Drake              Childs Play      0
573  Drake           Summer Sixteen      0
586  Drake               Right Hand      0
608  Drake                   Energy      0
610  Drake            Know Yourself      0
612  Drake                   Legend      0
614  Drake                 10 Bands      0
636  Drake             The Language      0
642  Drake           Worst Behavior      0
691  Drake      Hate Sleeping Alone      0
693  Drake              Shot For Me      0
699  Drake             Marvins Room      0

In [14]:
#Dataframe shape
df.shape

(809, 3)

In [15]:
#Save the dataframe as 'Billboard.csv'
df.to_csv('Billboard.csv', index=False)

#Read the dataset
dataset = pd.read_csv('Billboard.csv')
dataset

             Artist                           Title  Label
0        The Weeknd                 Blinding Lights      1
1    Olivia Rodrigo                        Good 4 U      1
2    Olivia Rodrigo                 Drivers License      1
3         Lil Nas X  Montero (Call Me By Your Name)      1
4               BTS                          Butter      1
..              ...                             ...    ...
804    Gwen Stefani                       Luxurious      0
805         Rihanna    If It's Lovin' That You Want      0
806       Lil Wayne                         Fireman      0
807     Alicia Keys                     Unbreakable      0
808   Rascal Flatts                 Skin (Sarabeth)      0

[809 rows x 3 columns]